/***************************************************************************
 *   Copyright (c) 2012 Andrew Robinson <andrewjrobinson@gmail.com>        *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#include <PreCompiled.h>
#ifndef _PreComp_
# include <QGridLayout>
#endif

#include "ToolPathDockWindow.h"
#include "UIManager.h"

#include "sstream"

namespace CamGui {

ToolPathDockWindow::ToolPathDockWindow(Gui::Document*  pcDocument, QWidget *parent)
  : DockWindow(pcDocument,parent)
{
	setWindowTitle(QString::fromUtf8("Tool Path"));

  textedit = new QTextEdit(this);
  textedit->setReadOnly(true);
  textedit->setLineWrapMode(QTextEdit::NoWrap);

  QGridLayout* pLayout = new QGridLayout(this);
  pLayout->setSpacing(0);
  pLayout->setMargin (0);
  pLayout->addWidget(textedit, 0, 0);

  resize( 600, 400 );
  clearSelection();

  // listen for ToolPath Selection events
  QObject::connect(&UIManager(), SIGNAL(updatedToolPathSelection(Cam::ToolPathFeature*)), this,
          SLOT(updatedToolPathSelection(Cam::ToolPathFeature*)));

//  setToolPath(QString::fromUtf8("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
//"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"\
//"p, li { white-space: pre-wrap; }\n"
//"</style></head><body style=\" font-family:'Cantarell'; font-size:11pt; font-weight:400; font-style:normal;\">\n"\
//"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">"\
//"<span style=\" font-family:'Courier'; font-size:9pt; color:#5c46ff;\">'''<br />"\
//"Generated by FreeCAD/CAM Module<br />Date: 2012-10-25 22:00<br />Document: Unnamed.fcstd<br />'''</span><span style=\" "\
//"font-family:'Courier'; font-size:9pt;\"><br /></span><span style=\" font-family:'Courier'; font-size:9pt; font-weight:600; "\
//"color:#666666;\"># Setup</span><span style=\" font-family:'Courier'; font-size:9pt;\"><br /></span><span style=\" "\
//"font-family:'Courier'; font-size:9pt; color:#0d8f94;\">MachineLibrary</span><span style=\" font-family:'Courier'; font-size:9pt;\""\
//">(</span><span style=\" font-family:'Courier'; font-size:9pt; color:#9b0000;\">'MyMachines'</span><span style=\" "\
//"font-family:'Courier'; font-size:9pt;\">)<br /></span><span style=\" font-family:'Courier'; font-size:9pt; color:#0d8f94;\">"\
//"SetMachine</span><span style=\" font-family:'Courier'; font-size:9pt;\">(</span><span style=\" font-family:'Courier'; "\
//"font-size:9pt; color:#9b0000;\">'3-Axis Desktop CNC'</span><span style=\" font-family:'Courier'; font-size:9pt;\">)<br />"\
//"</span><span style=\" font-family:'Courier'; font-size:9pt; color:#0d8f94;\">ToolLibrary</span><span style=\" "\
//"font-family:'Courier'; font-size:9pt;\">(</span><span style=\" font-family:'Courier'; font-size:9pt; color:#9b0000;\">"\
//"'Default'</span><span style=\" font-family:'Courier'; font-size:9pt;\">)<br /><br /></span><span style=\" font-family:"\
//"'Courier'; font-size:9pt; font-weight:600; color:#666666;\"># Box - Rough</span><span style=\" font-family:'Courier'; "\
//"font-size:9pt;\"><br /></span><span style=\" font-family:'Courier'; font-size:9pt; color:#0d8f94;\">SetTool</span><span "\
//"style=\" font-family:'Courier'; font-size:9pt;\">(</span><span style=\" font-family:'Courier'; font-size:9pt; color:#9b0000;\""\
//">'6.35mm Carbide'</span><span style=\" font-family:'Courier'; font-size:9pt;\">)<br /></span><span style=\" font-family:"\
//"'Courier'; font-size:9pt; font-weight:600; color:#9b0000;\">Rapid</span><span style=\" font-family:'Courier'; font-size:9pt;\">"\
//"(0,1,1)<br /></span><span style=\" font-family:'Courier'; font-size:9pt; font-weight:600; color:#9b0000;\">Rapid</span><span "\
//"style=\" font-family:'Courier'; font-size:9pt;\">(0,1,0.9)<br /></span><span style=\" font-family:'Courier'; font-size:9pt; "\
//"font-weight:600; color:#025000;\">Feed</span><span style=\" font-family:'Courier'; font-size:9pt;\">(0,1,0.5)<br /></span>"\
//"<span style=\" font-family:'Courier'; font-size:9pt; font-weight:600; color:#025000;\">Feed</span><span style=\" font-family:"\
//"'Courier'; font-size:9pt;\">(1,1,0.5)<br /></span><span style=\" font-family:'Courier'; font-size:9pt; font-weight:600; color:"\
//"#666666;\">#...</span><span style=\" font-family:'Courier'; font-size:9pt;\"><br /><br /></span><span style=\" font-family:"\
//"'Courier'; font-size:9pt; font-weight:600; color:#666666;\"># Box - Finish</span><span style=\" font-family:'Courier'; "\
//"font-size:9pt;\"><br /></span><span style=\" font-family:'Courier'; font-size:9pt; color:#0d8f94;\">SetTool</span><span "\
//"style=\" font-family:'Courier'; font-size:9pt;\">(</span><span style=\" font-family:'Courier'; font-size:9pt; color:#9b0000;\">"\
//"'3.175mm Ball'</span><span style=\" font-family:'Courier'; font-size:9pt;\">)</span></p></body></html>"));
}

ToolPathDockWindow::~ToolPathDockWindow() {
}

/**
 * Set the Toolpath to be displayed.  It expects the toolpath to be in HTML
 * format already.
 */
void ToolPathDockWindow::setToolPath(const QString &toolpath)
{
  textedit->setHtml(toolpath);
}

/**
 * Clear the output (i.e. no toolpath or machine program selected)
 */
void ToolPathDockWindow::clearSelection() {
    textedit->setText(QString::fromUtf8("No tool-path/machine program selected"));
}


/**
 * Receive messages to update the toolpath display
 */
void ToolPathDockWindow::updatedToolPathSelection(Cam::ToolPathFeature* toolpath) {
    if (toolpath != NULL) {

        const std::vector<std::string> tpcmds = toolpath->TPCommands.getValues();
        if (tpcmds.size() > 0) {

            // format the toolpath
            //TODO: do a colour coded rendering
            std::vector<std::string>::const_iterator it;
            std::stringstream ss;
            ss << "<p><b>Toolpath</b>:</p>" << std::endl;
            ss << "<ol>" << std::endl;
            for (it = tpcmds.begin(); it != tpcmds.end(); ++it)
                ss << "  <li><i>" << (*it) << "</i></li>" << std::endl;
            ss << "</ol>" << std::endl;

            // update display
            setToolPath(QString::fromStdString(ss.str()));
        }
        else
            clearSelection();
    }
    else
        clearSelection();
}

#include "moc_ToolPathDockWindow.cpp"

} /* namespace Cam */
